import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/Footer";



const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MarketIX",
  description: "Generated by create next app",
  // icons: {
  //   icon: ["/favicon.ico?v=4"],
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <meta name="google-site-verification" content="zDwBDmtTsRGAKVlJ1qtHFUiv5_JDUo3DOsEKGLBFLX8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `
              var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
              (function(){
                var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
                s1.async=true;
                s1.src='https://embed.tawk.to/67d08db949a4f3190f34c2bd/1im3aj81o';
                s1.charset='UTF-8';
                s1.setAttribute('crossorigin','*');
                s0.parentNode.insertBefore(s1,s0);
              })();
            `
          }}
        /> */}
      </head>
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <Navbar />
        
        <main className="flex-grow">
          {children}
        </main>
        
     
        
        <Footer />
      </body>
    </html>
  );
}
